// flow-typed signature: 78de8fb0e1cf4a80db39fa82e351064a
// flow-typed version: <<STUB>>/singlie_v^2.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'singlie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'singlie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'singlie/src/circular' {
  declare module.exports: any;
}

declare module 'singlie/src/linear' {
  declare module.exports: any;
}

declare module 'singlie/src/list' {
  declare module.exports: any;
}

declare module 'singlie/src/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'singlie/index' {
  declare module.exports: $Exports<'singlie'>;
}
declare module 'singlie/index.js' {
  declare module.exports: $Exports<'singlie'>;
}
declare module 'singlie/src/circular.js' {
  declare module.exports: $Exports<'singlie/src/circular'>;
}
declare module 'singlie/src/linear.js' {
  declare module.exports: $Exports<'singlie/src/linear'>;
}
declare module 'singlie/src/list.js' {
  declare module.exports: $Exports<'singlie/src/list'>;
}
declare module 'singlie/src/node.js' {
  declare module.exports: $Exports<'singlie/src/node'>;
}
