// flow-typed signature: 7de77c67ff7ed41a4b4ffbb3381708db
// flow-typed version: <<STUB>>/@csstools/normalize.css_v^10.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@csstools/normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@csstools/normalize.css' {
  declare module.exports: any;
}
